### ISSUE TITLE
TypeError: cannot perform reduce with flexible type

### ISSUE THREAD

**Issue by its0x4d** [EasyAI/Python-Trade-Indicators#1]
Hi i'm using get_MACD function and i use this function to get candles
candles = bot.get_klines(symbol="BTCUSDT", interval=bot.KLINE_INTERVAL_1MINUTE)
and this is my candles output:
[[unixtime, open, high, low, close, volume], ...]
and i get this error:
TypeError: cannot perform reduce with flexible type

**Comment by chrishsr** [comment]
how do you call the get_MACD function?
try:
`import technical_indicators as TI`
`MACD = TI.getMACD(candles['close'])`
